<a href="https://colab.research.google.com/github/VishnuSarathy/Stack-vishnu/blob/main/Week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<H1>Part 1</H1>

**Load the Dataset**

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('/content/sample_data/california_housing_train.csv')

In [ ]:
data.head(5)

In [ ]:
data.tail(10)

**Data Summary**

In [ ]:
data.describe()

In [ ]:
len(data["total_bedrooms"].unique())

**Data Transformation**

In [12]:
data['total_bedrooms_per_total_rooms'] = data["total_bedrooms"] / data["total_rooms"]

In [ ]:
data.describe()

In [ ]:
data["total_bedrooms_per_total_rooms"].mean()

In [ ]:
data["total_bedrooms_per_total_rooms"].std()

**Data Filtering**

This prints only the values of median_income

In [ ]:
arr = []
for i in data["median_income"]:
  if i> 5:
    print(i)

This prints all rows with median_income greater than 5

In [ ]:
data[data['median_income'] > 5]

This prints all rows with median_house_value less than 150000 and total_rooms grater than 1000

In [ ]:
data[(data['total_rooms'] > 10000) & (data['median_house_value'] < 150000)]

**Saving/Exporting**

This saves the above changed data set to modified.csv in sample_data folder

In [23]:
data.to_csv('/content/sample_data/modified.csv')

# Part 2

In [5]:
import numpy as np

Generating array

In [6]:
ar1 = np.arange(1,21)
print(ar1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


slicing the array to print even numbers

In [7]:
print(ar1[1:21:2])

[ 2  4  6  8 10 12 14 16 18 20]


Generating 2 d array

In [8]:
ar2 = np.random.randint(10, 101, size=(5, 4))
print(ar2)

[[38 60 84 88]
 [66 20 50 24]
 [16 88 27 95]
 [27 16 80 29]
 [41 58 36 17]]


slicing 2d array to print first 3 rows and 2 columns

In [9]:
print(ar2[0:3,0:2])

[[38 60]
 [66 20]
 [16 88]]


Array Manipulation

reshaping 1d to 2d array

In [10]:
ar1 = ar1.reshape(4, 5)
print(ar1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


Again using flatten to convert into 1d array

In [11]:
ar1 = ar1.flatten()
print(ar1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Using dot function of numpy to do matrix multiplication

In [12]:
ar3 = np.random.randint(0, 100, size=(5, 4)).transpose()
np.dot(ar2, ar3)

array([[11390, 15696, 12938, 10278, 11776],
       [ 4730,  5906,  4406,  7028,  9134],
       [ 9030, 16386, 14457, 10380,  9085],
       [ 6645,  7089,  5034,  4936,  7486],
       [ 3991,  8405,  6502,  8452,  9176]])

Creating g50 which is boolean index

In [51]:
ar4 = np.random.randint(0, 101, size=50)
print(ar4)
g50 = ar4>50
print(ar4[g50])

[54 38 17 63 33 76 33 97 29 74 30 19 92 46 29 58 28 20 73 76 37 29 20 49
 98 72 52 57 96 19 35 53 88 49 92 88 92  4 91 79 71 57 78 65  4 16 85 31
 48 66]
[54 63 76 97 74 92 58 73 76 98 72 52 57 96 53 88 92 88 92 91 79 71 57 78
 65 85 66]


ar5 represents fancy index of elements which needs to be printed

In [52]:
ar5 = [1,3,5,7]
print(ar4[ar5])

[38 63 76 97]


**Statistical Operations**

finding mean max sum along axis:0, i.e. columns

In [53]:
mean = ar2.mean(axis=0)
max = ar2.max(axis=0)
sum = ar2.sum(axis=0)
print(mean,max,sum)

[48.8 73.6 68.6 49.6] [83 92 98 91] [244 368 343 248]


In [55]:
mask = ar2 > mean
print(ar2[mask])
print(ar2)

[70 69 91 82 88 65 81 98 83 92 71]
[[70 65 69 91]
 [10 72 82 88]
 [65 81 98 15]
 [83 92 23 42]
 [16 58 71 12]]


# Part 3

**Loops and Conditional Statements**

Printing fibonnaci

In [59]:
s = 1
pre =0
print(0)
while(s<100):
  print(s)
  temp = pre
  pre = s
  s = s+temp

0
1
1
2
3
5
8
13
21
34
55
89


In [61]:
for i in range(1,51):
  if i%15 == 0:
    print(i,"\tFizzBuzz")
  elif i%5 == 0:
    print(i,"\tBuzz")
  elif i%3 == 0:
    print(i,"\tFizz")

3 	Fizz
5 	Buzz
6 	Fizz
9 	Fizz
10 	Buzz
12 	Fizz
15 	FizzBuzz
18 	Fizz
20 	Buzz
21 	Fizz
24 	Fizz
25 	Buzz
27 	Fizz
30 	FizzBuzz
33 	Fizz
35 	Buzz
36 	Fizz
39 	Fizz
40 	Buzz
42 	Fizz
45 	FizzBuzz
48 	Fizz
50 	Buzz


**Variable-Length Arguments**

In [79]:
l = int(input("Enter no of elements: "))
lis = []
for i in range(l):
  lis.append(int(input()))
if l%2 != 0:
  print(lis[l//2])
else:
  print((lis[l//2]+lis[l//2 -1])/2)

Enter no of elements: 4
1
2
3
4
2.5


In [85]:
lis = list(map(int, input().split()))
s = 0
for i in lis:
  s+=i
print("Avg: ",s/len(lis))

1 2 3 4 5
3.0


**Error Handling**

In [2]:
a = int(input("Enter Numerator"))
b = int(input("Enter Denominator"))
try:
  print(a/b)
except ZeroDivisionError:
  print("Denominator Should not be zero")

Enter Numerator2
Enter Denominator0
Denominator Should not be zero


# Part 4

In [3]:
import numpy as np
ar1 = np.random.randint(0,11,size=(3,3,3))
print(ar1)

[[[ 9  3  4]
  [ 6  3  2]
  [10  4  9]]

 [[ 6  6  5]
  [ 9 10  1]
  [ 1  7  3]]

 [[10  3  5]
  [ 4  1  1]
  [ 4  5  2]]]


In [4]:
ar1 = np.swapaxes(ar1, 0, 1)
print(ar1)

[[[ 9  3  4]
  [ 6  6  5]
  [10  3  5]]

 [[ 6  3  2]
  [ 9 10  1]
  [ 4  1  1]]

 [[10  4  9]
  [ 1  7  3]
  [ 4  5  2]]]
